### PR TITLE
Code refactoring of Parany.run

### PR DESCRIPTION
**Pull request by darrenldl**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Thanks a lot Darren!
I just did some code cleaning but I could not have guessed those magical type annotations.

**Comment by darrenldl** [comment]
All good. That was a nice problem to think about before sleep.

I was mainly thinking along the lines of making the chunk of code polymorphic so the types of `demux, work, mux` and `(idemux demux), (iwork work), (imux mux)` would not need to unify (the  unification between types `'a` and `int * 'b` seemed to be the typing error). And so moving said chunk into a separate function with polymorphic arguments was the approach used.

Locally abstract types (the `let f (type ...) ...` syntax) just happened to be an easy way to make sure the arguments are actually polymorphic.

I actually went to read the manual after your comment, and the manual reads that locally abstract types don't actually render the types polymorphic, but it seems to work fine in `utop` and in my code, so I'm not fully sure if that's the right choice, but ye.

**Comment by UnixJunkie** [comment]
I ran the tests (./test.sh) and they passed. Don't worry.

**Comment by UnixJunkie** [comment]
Apparently, the (type a b) annotation introduced implies an OCaml version constraint: OCaml >= 4.03.0.
It would be nice (though not mandatory) if we did not add such a version constraint.

**Pull request merged**
