### PR TITLE
Drop ocaml prefix for semaphore name to comply with OSX 31 char limit

### LINKED ISSUE #12: Named semaphore size limit on OSX
turns out to be a bit short: [PSEMNAMLEN](https://github.com/st3fan/osx-10.9/blob/master/xnu-2422.1.72/bsd/sys/posix_sem.h#L54).

Can we `s/ocaml_//` [here](https://github.com/UnixJunkie/parany/blob/master/parany.ml#L25) ?
Or maybe (or also) change `pid` to `p` and `sem` to `s` ?

### PR DESCRIPTION
**Pull request by rleonid**
To fix #12

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I am sending right now a bugfix release in opam. In the meantime, there is tag v1.0.3 if you need.
Thanks for the fix and for testing on osx.
Don't hesitate to tell me if you see some nice acceleration obtained thanks to parany.

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-repository/pull/10017

**Comment by rleonid** [comment]
It has been great and easy to use! I don't think that I've necessarily optimized my data structures correctly as it seems like the per-unit processing time has gone up (10%-20%) in the parallel version. But for obtaining naive-parallelization for when I want to flood 24 cores with work after half-an-hour's time of tweaking the code, the library is pretty awesome! So big thanks.

**Comment by UnixJunkie** [comment]
I added a chunk size parameter. I need to test more but it allows to lower the overhead per element to process. For example, it allows to process elements by groups of ten.
You can play with this parameter to optimize performances for your use case.

**Pull request merged**
